version: '3'

networks:
  pizzeria:
    driver: bridge

services:
  mysql-db:
    image: mysql:8
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: toor
    networks:
      - pizzeria

  servlet:
    build: ./backend/pizzeria-servlet
    image: ig-master/pizzeria:servlet
    ports:
      - 127.0.0.1:8080:8080
    environment:
      JAVA_OPTS: "-DdataSource.jdbcUrl=mysql://mysql-db:3306/pizzeria?useSSL=false\\&allowPublicKeyRetrieval=true"
    networks:
      - pizzeria
    depends_on:
      - mysql-db
  vertx:
    build: ./backend/pizzeria-vertx
    image: ig-master/pizzeria:vertx
    ports:
      - 127.0.0.1:8081:8081
    environment:
      SERVER_PORT: 8081
      JAVA_OPTS: "-DdataSource.jdbcUrl=mysql://mysql-db:3306/pizzeria?useSSL=false&allowPublicKeyRetrieval=true"
    networks:
      - pizzeria
  boot:
    build: ./backend/pizzeria-boot
    image: ig-master/pizzeria:boot
    ports:
      - 127.0.0.1:8082:8082
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/pizzeria?useSSL=false&allowPublicKeyRetrieval=true"
    networks:
      - pizzeria
  webflux:
    build: ./backend/pizzeria-webflux
    image: ig-master/pizzeria:webflux
    ports:
      - 127.0.0.1:8083:8083
    environment:
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/pizzeria?useSSL=false&allowPublicKeyRetrieval=true"
    networks:
      - pizzeria
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.builder
    image: ig-master/pizzeria-ui
    ports:
      - 80:80
    depends_on:
      - mysql-db
